services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'  # Port mapping for external access if needed

  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'  # Port mapping for external access if needed
